### ISSUE TITLE
Top posts this week

### ISSUE THREAD

**Issue by brendt** [brendt/aggregate.stitcher.io#1]
Top posts are posts with the most upvotes the past week.

**Comment by monaam** [comment]
So just to get the idea straight,
Top posts are customized for users right? so I'll only see relevant topics compared to either my reading history, or my followed tags and keywords. Or is it an absolute ranking of all posts?

**Comment by brendt** [comment]
@monaam I'd like to keep the first iteration fairly simple: top posts are the posts that received the most upvotes and views the post week, optionally filtered by tag. Note that views don't count as much as votes. I was thinking about calculating a "popularity weight" per post, where a vote counts, for example, for 3 points, and a view for 1.

Personally, I never liked platforms who tried to make "educated guesses" as to what I want to read. Just give me a full overview in chronological order, with at most a simple filter. So I'm hesitant to add a personalised view. But I'm of course open for input.

**Comment by brendt** [comment]
Right now, top posts are the ones with the most views, as voting is disabled.
