### ISSUE TITLE
Feed performance

### ISSUE THREAD

**Issue by brendt** [brendt/aggregate.stitcher.io#106]
Right now there's a naive page cache implementation: every user has its own cached version of the "discover" feed, and every time a change happens in the system (a new post, a vote, a view) that cache is cleared and rebuild only after the next page refresh.

In practice this approach results in 95% cache misses, since users simply don't often refresh the page, and chances are very likely a change happened that causes the cache to be invalid.

My original idea was to rebuild the page cache every time a change happens, instead of invalidating it and waiting for the next page refresh for that user. The problem with that approach is server performance: every time a change happens there should be a page cache rebuild triggered for every user. This would grow out of hand exponentially very fast.

The next idea was to have page cache run on a cron job, and not invalidate it when changes happen in the system. This in turn introduces a UX issue: if users vote, they don't want to wait a minute or so before their vote shows up.

So I'd appreciate some input on this one, not sure what the best approach is 😅

**Comment by lukgru** [comment]
Maybe caching full page for every user is not good idea. Maybe a better solution would be partial cache?
