### ISSUE TITLE
No new posts coming in

### ISSUE THREAD

**Issue by PtrTn** [brendt/aggregate.stitcher.io#117]
Either everyone decided to stop posting from the 7th of march or there's an error in loading the feeds causing no new ones to come in. Are you aware of this?

**Comment by brendt** [comment]
I'm aware, I'm in the process of migrating the project since I'm unable to maintain it anymore. Takes a little longer than expected.

**Comment by PtrTn** [comment]
Thanks for letting me know. Good luck with the migration 👌
