### ISSUE TITLE
Tag syncing

### ISSUE THREAD

**Issue by brendt** [brendt/aggregate.stitcher.io#2]
Lots of improvements have to be made to better match tags with content. I'd love some input on this.

Right now tags are predefined here: https://github.com/brendt/aggregate.stitcher.io/blob/master/app/tags.yaml

Every tag has a bunch of keywords. The content of a post is scanned and tags are counted here: https://github.com/brendt/aggregate.stitcher.io/blob/master/app/Domain/Post/Decorators/RssEntryDecorator.php

We'll need to either improve the tags and keywords, or find another way of tagging content.

Also, `RssEntryDecorator` needs some cleaning up 🙈

**Comment by monaam** [comment]
Why not upgrading it a bit, and use [Open Calais](http://www.opencalais.com/open-calais-products/) ?

Scan for tags and determine (according to tags occurences) the topic of the article

**Comment by brendt** [comment]
I did consider using a third party service, but am hesitant because of performance and pricing. There's a lot of data that we need to handle, and relying on a third party service via a HTTP API will slow things down a lot.

So I'd like to focus on a simple yet effective way of tagging content ourselves, or using an existing PHP library. Though I'm unaware of a good one in existence.

One important requirement is that the platform should keep managing tags. I don't want some kind of AI creating tags on the fly. Tags will be the way of filtering in the future, and there shouldn't be 101 possible ways of tagging content; that's just confusing for the reader.

It's about finding the right balance between flexibility and correctness.

**Comment by brendt** [comment]
I made some improvements by also looking at the category tags in RSS files, and lowering the tag treshold. There's still lots of room for improvement though
