### ISSUE TITLE
Multiple languages

### ISSUE THREAD

**Issue by filips123** [brendt/aggregate.stitcher.io#56]
There should be support for multiple languages. Users should also be able to sort posts by language.

**Comment by brendt** [comment]
A good idea! Here's my suggestion:

- [ ] Optionally specify a language when adding a source
- [ ] A logged in user can optionally select one or more languages, which will filter the feed automatically
- [ ] Add an filter to the feed. Maybe we should also add a `/{language}` route, or `{language}.aggregate` subdomains.

**Comment by MatanYadaev** [comment]
I'll be glad to implement this feature. Should I attach tests to my PR?

**Comment by brendt** [comment]
Awesome, thanks! One or two tests would be nice, but I'll be happy to help you with it when you've send the PR.

**Comment by brendt** [comment]
This feature has been deployed 👍

- There's a `language` filter available in post overviews, eg: https://aggregate.stitcher.io/discover?filter[language]=nl
- A user can set multiple languages
- Sources and posts can specify their language. Right now a post's language is determined by its source, though we might need to improve this in the future, in case of multi-lingual blogs.

**Comment by bueltge** [comment]
How it is possible to set more as one language key, like `discover?filter[language]=nl+en` ?

**Comment by brendt** [comment]
That's not possible yet, I'll fix it soon
