### ISSUE TITLE
Incorrect redirect for relative feed link

### ISSUE THREAD

**Issue by ssnepenthe** [brendt/aggregate.stitcher.io#65]
Awesome project!

I just clicked a link for "Serverless case study: PrettyCI and Laravel Queues" on mnapoli.fr and got a 404.

The aggregate.stitcher.io link is:

* https://aggregate.stitcher.io/8756c023-5720-4590-87cb-989c13e243f1

Which is redirecting to:

* https://aggregate.stitcher.io/serverless-case-study-prettyci?ref=aggregate.stitcher.io

Instead of:

* https://mnapoli.fr/serverless-case-study-prettyci/

From a quick look at the feed on mnapoli.fr I am assuming it is an import issue with relative feed links - here is the feed entry:

```
<entry>
    <title>Serverless case study: PrettyCI and Laravel Queues</title>
    <link href="/serverless-case-study-prettyci/"/>
    <updated>2019-03-21T18:00:00+00:00</updated>
</entry>
```

**Comment by brendt** [comment]
Good catch, going to fix this immediately. Thanks for taking the time to report this!

**Comment by brendt** [comment]
It's fixed now, thanks again for making an issue!
