### ISSUE TITLE
Implement an aggregated RSS feed

### ISSUE THREAD

**Issue by PtrTn** [brendt/aggregate.stitcher.io#74]
I love the blog aggregation you've created as this is an easy way to keep up-to-date with all sorts of PHP-related stuff. Personally I would like to keep myself and colleagues informed whenever a new blog is posted. One way of doing so could be to implement an RSS feed, which can be used by a slack bot to notify our developers. 

I'd like to know if you think such a solution would fit in this application? Additionally, if you could think of other ways to recieve notifications for new blog posts I'm all ears.

Personally I don't mind implementing the feature myself, but I'd like to know if there's demand for it up front 😄

**Comment by brendt** [comment]
It's a good idea, feel free to send a PR, and ask me questions anytime!

**Comment by brendt** [comment]
The basic feed has been merged and deployed: https://aggregate.stitcher.io/rss

However, it will need improvements before actually being usable. I opened an issue for this: #80
