### ISSUE TITLE
Multiple feeds for one user

### ISSUE THREAD

**Issue by filips123** [brendt/aggregate.stitcher.io#77]
Add support to create multiple "my feeds" for one user. This is useful if the user has multiple blogs.

**Comment by brendt** [comment]
Users can already have multiple sources, but this is not allowed by design. It might be enabled in the future.

**Comment by filips123** [comment]
Why is it not allowed?

**Comment by brendt** [comment]
At the time I considered making this a "premium" feature in combination with in-depth statistics. But I've since changed my mind on that topic. If you want to give it a shot and submit a PR, I'll be happy to review it.

**Comment by filips123** [comment]
Where should this feature be added in code?

All current feeds should be listed on My feeds" page. Each feed should "URL", "Twitter handle" and "This blog is about" inputs and "Save" and "Delete" buttons.
But under all current feeds, there should be a button "Add a new feed" which would all new section for the new feed.

**Comment by brendt** [comment]
In `/profile/sources` we'd have to add an overview, a table like in the admin section. I would provide a new detail page to edit and create sources, and another page to confirm a source deletion.

The flow is the same as in [AdminSourcesController](https://github.com/brendt/aggregate.stitcher.io/blob/master/app/App/Http/Controllers/AdminSourcesController.php), but with another form and other validation rules (you should also check whether the source actually belongs to the user when editing)
