### ISSUE TITLE
Improvements to RSS feed

### ISSUE THREAD

**Issue by brendt** [brendt/aggregate.stitcher.io#80]
Because of the potential huge amounts of data, we need to make sure the RSS feed doesn't become too slow. That's why I suggest adding two features:

- [x] Filter by topic: `/rss?topic=php` or `/rss?topic[]=php&topic[]=javascript`
- [x] Limit posts, only show posts of the past month

**Comment by brendt** [comment]
@PtrTn would you be interested in taking a look at this? Please don't feel pressured, I'm happy to do it myself :)

**Comment by PtrTn** [comment]
@brendt I'm fine with picking this up. You'll see a PR coming up

**Comment by brendt** [comment]
PR has been merged and deployed 👍
