### ISSUE TITLE
Handle failed RSS sync jobs

### ISSUE THREAD

**Issue by brendt** [brendt/aggregate.stitcher.io#9]
When a sync job fails, there should be a way for admins to take a look at what went wrong and how to fix it.

**Comment by zakius** [comment]
I'll list a possible kinds of failures to consider, each one of them may require different approach to handle

- DNS failure (the requested domain can't be resolved)
- timeout
- proxy failing to connect to target server (e.g. Cloudflare reporting origin ~~downtime~~ problem) (possibly seen as 200 with invalid content or 500 class)
- encryption issues
    - outdated cert
    - invalid (e.g. wrong domain) cert
    - unsupported algorithm/protocol
- origin returning unexpected response:
    - 200 class with invalid content
    - 300 class (following temporary redirects is reasonable, but in case of permanent should we update the entry automatically?)
    - 400 class
    - 500 class

**Comment by brendt** [comment]
Thanks @zakius, I really appreciate your input! It's also important to keep in mind that we're not an uptime checker. I think there's three categories we have to handle: 

- Unreachable RSS feeds, whatever the cause; a server side problem at the source's side. We should notify the source's owner after a while, and eventually disable the source is no action is taken.
- Unparsable RSS feeds, which we should notify the owner of immediately, and maybe even several times, with a few days interval. If the issue isn't fixed after a given amount of time, the source should be disabled.
- A problem on our side: in this case admins should be notified immediately, I should also look into setting up bugsnag.

**Comment by zakius** [comment]
sounds about right, though some issues' classification may be disputable (e.g. server owner upgraded configuration willingly and now secure connection fails, it may need in-depth analysis to make sure it's not misconfiguration on our side that disallows newer protocols and not source owner that went crazy with increasing requirements and cutting off half of their users)

**Comment by brendt** [comment]
We have horizon in place which highlights failed jobs. Together with source validation this issue isn't relevant anymore.
